language: php
php:
  - nightly
install:
  - composer install --dev

services:
  - postgresql

before_script:
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql -U postgres -c 'create extension postgis;'

addons:
  postgresql: "9.4"
  apt:
    packages:
      - postgresql-9.4-postgis-2.3
